id: A76991150
title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā Combined
  with Her Root Mantra'
type: translation
pechas:
- IB5F2C161
- I26CDD03D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:11.263113
  last_modified_at: 2023-01-04 12:36:11.263129
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IB5F2C161/F888: 29D3
  I26CDD03D/EA7B: 29D3
